name: XiaoEnchant
main: zbv5.cn.XiaoEnchant.Main
version: 1.0.0
api: 1.0.0
author: 逍遥
commands:
  XiaoEnchant:
    description: 逍式附魔
    aliases: ["xe","xench"]
permissions:
  XiaoEnchant.admin:
    description: 使用全部功能所需权限
    default: op